spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db_test;MODE=MySQL
    username: sa
    password:

#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/chat_dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
#    username: root
#    password: 1234