server:
  port: 8070
spring:
  profiles:
    active: dev
    include: secret
  logging:
    level:
      com.ll.chat_ai: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE
      org.hibernate.orm.jdbc.extract: TRACE
      org.springframework.transaction.interceptor: TRACE
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          show-sql: true
          format_sql: true
          user_sql_comments: true
          defualt_batch_fetch_size: 100